model:
  name: "Qwen/Qwen3-4B"  # Change this to your desired model
  dtype: "float16"
  trust_remote_code: true

sampling_strategies:
  - name: "default"
    temperature: 0.7
    top_p: 0.9
    max_tokens: 1000
  - name: "creative"
    temperature: 1.2
    top_p: 0.95
    min_p: 0.05
    max_tokens: 1000
  - name: "precise"
    temperature: 0.3
    top_p: 0.8
    max_tokens: 1000

scoring:
  format:
    answer_tag: "<answer>"
  strategies:
    exact_match:
      default_case_sensitive: false
      default_allow_partial: false
    numeric:
      default_tolerance: 0
      allow_scientific_notation: true
    list:
      default_order_matters: false
      default_allow_partial: false
      default_separators: [",", ";", "and", "&"]

output:
  base_dir: "output"
  save_individual: true
  save_consolidated: true
  metadata:
    include_timestamp: true
    include_model_version: true
    include_sampling_params: true 